# Generated by Django 2.2.13 on 2020-06-22 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_imange'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='imange',
            new_name='image',
        ),
    ]
